export const countries = [
  {
    name: "Countries",
    array: [
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
      "USA",
      "Canada",
    ],
  },
];
export const categories = [
  {
    name: "Languages",
    array: [
      "Yoruba",
      "French",
      "Spanish",
      "English",
      "Yoruba",
      "French",
      "Spanish",
      "English",
      "Yoruba",
      "French",
      "Spanish",
      "English",
      "Yoruba",
      "French",
      "Spanish",
      "English",
      "Yoruba",
      "French",
      "Spanish",
      "English",
      "Yoruba",
      "French",
      "Spanish",
      "English",
    ],
  },
  {
    name: "Music",
    array: ["Accordion", "Guitar", "Sound Engineering", "Music Production"],
  },
  {
    name: "Sports",
    array: ["Gym & Sports", "Karate", "Judo", "Taekwondo"],
  },
  {
    name: "Art & Craft",
    array: ["Knitting", "Photography", "Videography", "Sewing Class"],
  },
  {
    name: "Health & Wellness",
    array: ["Yoga", "CPR"],
  },
];
